credentials:
  usernames:
    example_user:
      email: user@example.com
      name: Example User
      password: "<PASTE_HASHED_PASSWORD_HERE>"

cookie:
  name: expense_manager_auth
  key: "change_this_to_a_random_secret_key"
  expiry_days: 30

preauthorized:
  emails: []
